name: nocix
description: Nocix VPN Professional
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  wireguard_flutter: ^0.1.3
  unity_ads_plugin: ^0.3.1 # Plugin de Anúncios
  file_picker: ^8.0.0 # Para importar servidores
  google_fonts: ^6.1.0 # Para tipografia profissional
  intl: ^0.19.0 # Para formatação de números

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # Gera os ícones automaticamente

# CONFIGURAÇÃO DO ÍCONE (O Codemagic lerá isto)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/LOGO.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/LOGO.png
    - assets/FUNDO.png
